# Generated by Django 3.1.1 on 2020-09-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=10)),
                ('check', models.CharField(max_length=40)),
                ('end', models.CharField(max_length=40)),
                ('cht', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=75)),
                ('subject', models.TextField()),
                ('feed', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=100)),
                ('room_no', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_no', models.BigIntegerField()),
            ],
        ),
    ]
